/*
 * Edge Application API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreateApplicationRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-05T18:30:12.901597Z[GMT]", comments = "Generator version: 7.12.0")
public class CreateApplicationRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_APPLICATION_ACCELERATION = "application_acceleration";
  @SerializedName(SERIALIZED_NAME_APPLICATION_ACCELERATION)
  @javax.annotation.Nullable
  private Boolean applicationAcceleration;

  public static final String SERIALIZED_NAME_DELIVERY_PROTOCOL = "delivery_protocol";
  @SerializedName(SERIALIZED_NAME_DELIVERY_PROTOCOL)
  @javax.annotation.Nullable
  private String deliveryProtocol;

  public static final String SERIALIZED_NAME_ORIGIN_TYPE = "origin_type";
  @SerializedName(SERIALIZED_NAME_ORIGIN_TYPE)
  @javax.annotation.Nullable
  private String originType;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  @javax.annotation.Nullable
  private String address;

  public static final String SERIALIZED_NAME_MINIMUM_TLS_VERSION = "minimum_tls_version";
  @SerializedName(SERIALIZED_NAME_MINIMUM_TLS_VERSION)
  @javax.annotation.Nullable
  private String minimumTlsVersion;

  public static final String SERIALIZED_NAME_ORIGIN_PROTOCOL_POLICY = "origin_protocol_policy";
  @SerializedName(SERIALIZED_NAME_ORIGIN_PROTOCOL_POLICY)
  @javax.annotation.Nullable
  private String originProtocolPolicy;

  public static final String SERIALIZED_NAME_HOST_HEADER = "host_header";
  @SerializedName(SERIALIZED_NAME_HOST_HEADER)
  @javax.annotation.Nullable
  private String hostHeader;

  public static final String SERIALIZED_NAME_BROWSER_CACHE_SETTINGS = "browser_cache_settings";
  @SerializedName(SERIALIZED_NAME_BROWSER_CACHE_SETTINGS)
  @javax.annotation.Nullable
  private String browserCacheSettings;

  public static final String SERIALIZED_NAME_CDN_CACHE_SETTINGS = "cdn_cache_settings";
  @SerializedName(SERIALIZED_NAME_CDN_CACHE_SETTINGS)
  @javax.annotation.Nullable
  private String cdnCacheSettings;

  public static final String SERIALIZED_NAME_BROWSER_CACHE_SETTINGS_MAXIMUM_TTL = "browser_cache_settings_maximum_ttl";
  @SerializedName(SERIALIZED_NAME_BROWSER_CACHE_SETTINGS_MAXIMUM_TTL)
  @javax.annotation.Nullable
  private Long browserCacheSettingsMaximumTtl;

  public static final String SERIALIZED_NAME_CDN_CACHE_SETTINGS_MAXIMUM_TTL = "cdn_cache_settings_maximum_ttl";
  @SerializedName(SERIALIZED_NAME_CDN_CACHE_SETTINGS_MAXIMUM_TTL)
  @javax.annotation.Nullable
  private Long cdnCacheSettingsMaximumTtl;

  public static final String SERIALIZED_NAME_DEBUG_RULES = "debug_rules";
  @SerializedName(SERIALIZED_NAME_DEBUG_RULES)
  @javax.annotation.Nullable
  private Boolean debugRules;

  public static final String SERIALIZED_NAME_SUPPORTED_CIPHERS = "supported_ciphers";
  @SerializedName(SERIALIZED_NAME_SUPPORTED_CIPHERS)
  @javax.annotation.Nullable
  private String supportedCiphers;

  public static final String SERIALIZED_NAME_HTTP_PORT = "http_port";
  @SerializedName(SERIALIZED_NAME_HTTP_PORT)
  @javax.annotation.Nullable
  private Object httpPort = null;

  public static final String SERIALIZED_NAME_HTTPS_PORT = "https_port";
  @SerializedName(SERIALIZED_NAME_HTTPS_PORT)
  @javax.annotation.Nullable
  private Object httpsPort = null;

  public static final String SERIALIZED_NAME_L2_CACHING = "l2_caching";
  @SerializedName(SERIALIZED_NAME_L2_CACHING)
  @javax.annotation.Nullable
  private Boolean l2Caching;

  public static final String SERIALIZED_NAME_HTTP3 = "http3";
  @SerializedName(SERIALIZED_NAME_HTTP3)
  @javax.annotation.Nullable
  private Boolean http3;

  public static final String SERIALIZED_NAME_WEBSOCKET = "websocket";
  @SerializedName(SERIALIZED_NAME_WEBSOCKET)
  @javax.annotation.Nullable
  private Boolean websocket;

  public CreateApplicationRequest() {
  }

  public CreateApplicationRequest name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public CreateApplicationRequest applicationAcceleration(@javax.annotation.Nullable Boolean applicationAcceleration) {
    this.applicationAcceleration = applicationAcceleration;
    return this;
  }

  /**
   * Get applicationAcceleration
   * @return applicationAcceleration
   */
  @javax.annotation.Nullable
  public Boolean getApplicationAcceleration() {
    return applicationAcceleration;
  }

  public void setApplicationAcceleration(@javax.annotation.Nullable Boolean applicationAcceleration) {
    this.applicationAcceleration = applicationAcceleration;
  }


  public CreateApplicationRequest deliveryProtocol(@javax.annotation.Nullable String deliveryProtocol) {
    this.deliveryProtocol = deliveryProtocol;
    return this;
  }

  /**
   * Get deliveryProtocol
   * @return deliveryProtocol
   */
  @javax.annotation.Nullable
  public String getDeliveryProtocol() {
    return deliveryProtocol;
  }

  public void setDeliveryProtocol(@javax.annotation.Nullable String deliveryProtocol) {
    this.deliveryProtocol = deliveryProtocol;
  }


  public CreateApplicationRequest originType(@javax.annotation.Nullable String originType) {
    this.originType = originType;
    return this;
  }

  /**
   * Get originType
   * @return originType
   */
  @javax.annotation.Nullable
  public String getOriginType() {
    return originType;
  }

  public void setOriginType(@javax.annotation.Nullable String originType) {
    this.originType = originType;
  }


  public CreateApplicationRequest address(@javax.annotation.Nullable String address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @javax.annotation.Nullable
  public String getAddress() {
    return address;
  }

  public void setAddress(@javax.annotation.Nullable String address) {
    this.address = address;
  }


  public CreateApplicationRequest minimumTlsVersion(@javax.annotation.Nullable String minimumTlsVersion) {
    this.minimumTlsVersion = minimumTlsVersion;
    return this;
  }

  /**
   * Get minimumTlsVersion
   * @return minimumTlsVersion
   */
  @javax.annotation.Nullable
  public String getMinimumTlsVersion() {
    return minimumTlsVersion;
  }

  public void setMinimumTlsVersion(@javax.annotation.Nullable String minimumTlsVersion) {
    this.minimumTlsVersion = minimumTlsVersion;
  }


  public CreateApplicationRequest originProtocolPolicy(@javax.annotation.Nullable String originProtocolPolicy) {
    this.originProtocolPolicy = originProtocolPolicy;
    return this;
  }

  /**
   * Get originProtocolPolicy
   * @return originProtocolPolicy
   */
  @javax.annotation.Nullable
  public String getOriginProtocolPolicy() {
    return originProtocolPolicy;
  }

  public void setOriginProtocolPolicy(@javax.annotation.Nullable String originProtocolPolicy) {
    this.originProtocolPolicy = originProtocolPolicy;
  }


  public CreateApplicationRequest hostHeader(@javax.annotation.Nullable String hostHeader) {
    this.hostHeader = hostHeader;
    return this;
  }

  /**
   * Get hostHeader
   * @return hostHeader
   */
  @javax.annotation.Nullable
  public String getHostHeader() {
    return hostHeader;
  }

  public void setHostHeader(@javax.annotation.Nullable String hostHeader) {
    this.hostHeader = hostHeader;
  }


  public CreateApplicationRequest browserCacheSettings(@javax.annotation.Nullable String browserCacheSettings) {
    this.browserCacheSettings = browserCacheSettings;
    return this;
  }

  /**
   * Get browserCacheSettings
   * @return browserCacheSettings
   */
  @javax.annotation.Nullable
  public String getBrowserCacheSettings() {
    return browserCacheSettings;
  }

  public void setBrowserCacheSettings(@javax.annotation.Nullable String browserCacheSettings) {
    this.browserCacheSettings = browserCacheSettings;
  }


  public CreateApplicationRequest cdnCacheSettings(@javax.annotation.Nullable String cdnCacheSettings) {
    this.cdnCacheSettings = cdnCacheSettings;
    return this;
  }

  /**
   * Get cdnCacheSettings
   * @return cdnCacheSettings
   */
  @javax.annotation.Nullable
  public String getCdnCacheSettings() {
    return cdnCacheSettings;
  }

  public void setCdnCacheSettings(@javax.annotation.Nullable String cdnCacheSettings) {
    this.cdnCacheSettings = cdnCacheSettings;
  }


  public CreateApplicationRequest browserCacheSettingsMaximumTtl(@javax.annotation.Nullable Long browserCacheSettingsMaximumTtl) {
    this.browserCacheSettingsMaximumTtl = browserCacheSettingsMaximumTtl;
    return this;
  }

  /**
   * Get browserCacheSettingsMaximumTtl
   * @return browserCacheSettingsMaximumTtl
   */
  @javax.annotation.Nullable
  public Long getBrowserCacheSettingsMaximumTtl() {
    return browserCacheSettingsMaximumTtl;
  }

  public void setBrowserCacheSettingsMaximumTtl(@javax.annotation.Nullable Long browserCacheSettingsMaximumTtl) {
    this.browserCacheSettingsMaximumTtl = browserCacheSettingsMaximumTtl;
  }


  public CreateApplicationRequest cdnCacheSettingsMaximumTtl(@javax.annotation.Nullable Long cdnCacheSettingsMaximumTtl) {
    this.cdnCacheSettingsMaximumTtl = cdnCacheSettingsMaximumTtl;
    return this;
  }

  /**
   * Get cdnCacheSettingsMaximumTtl
   * @return cdnCacheSettingsMaximumTtl
   */
  @javax.annotation.Nullable
  public Long getCdnCacheSettingsMaximumTtl() {
    return cdnCacheSettingsMaximumTtl;
  }

  public void setCdnCacheSettingsMaximumTtl(@javax.annotation.Nullable Long cdnCacheSettingsMaximumTtl) {
    this.cdnCacheSettingsMaximumTtl = cdnCacheSettingsMaximumTtl;
  }


  public CreateApplicationRequest debugRules(@javax.annotation.Nullable Boolean debugRules) {
    this.debugRules = debugRules;
    return this;
  }

  /**
   * Get debugRules
   * @return debugRules
   */
  @javax.annotation.Nullable
  public Boolean getDebugRules() {
    return debugRules;
  }

  public void setDebugRules(@javax.annotation.Nullable Boolean debugRules) {
    this.debugRules = debugRules;
  }


  public CreateApplicationRequest supportedCiphers(@javax.annotation.Nullable String supportedCiphers) {
    this.supportedCiphers = supportedCiphers;
    return this;
  }

  /**
   * Get supportedCiphers
   * @return supportedCiphers
   */
  @javax.annotation.Nullable
  public String getSupportedCiphers() {
    return supportedCiphers;
  }

  public void setSupportedCiphers(@javax.annotation.Nullable String supportedCiphers) {
    this.supportedCiphers = supportedCiphers;
  }


  public CreateApplicationRequest httpPort(@javax.annotation.Nullable Object httpPort) {
    this.httpPort = httpPort;
    return this;
  }

  /**
   * Get httpPort
   * @return httpPort
   */
  @javax.annotation.Nullable
  public Object getHttpPort() {
    return httpPort;
  }

  public void setHttpPort(@javax.annotation.Nullable Object httpPort) {
    this.httpPort = httpPort;
  }


  public CreateApplicationRequest httpsPort(@javax.annotation.Nullable Object httpsPort) {
    this.httpsPort = httpsPort;
    return this;
  }

  /**
   * Get httpsPort
   * @return httpsPort
   */
  @javax.annotation.Nullable
  public Object getHttpsPort() {
    return httpsPort;
  }

  public void setHttpsPort(@javax.annotation.Nullable Object httpsPort) {
    this.httpsPort = httpsPort;
  }


  public CreateApplicationRequest l2Caching(@javax.annotation.Nullable Boolean l2Caching) {
    this.l2Caching = l2Caching;
    return this;
  }

  /**
   * Get l2Caching
   * @return l2Caching
   */
  @javax.annotation.Nullable
  public Boolean getL2Caching() {
    return l2Caching;
  }

  public void setL2Caching(@javax.annotation.Nullable Boolean l2Caching) {
    this.l2Caching = l2Caching;
  }


  public CreateApplicationRequest http3(@javax.annotation.Nullable Boolean http3) {
    this.http3 = http3;
    return this;
  }

  /**
   * Get http3
   * @return http3
   */
  @javax.annotation.Nullable
  public Boolean getHttp3() {
    return http3;
  }

  public void setHttp3(@javax.annotation.Nullable Boolean http3) {
    this.http3 = http3;
  }


  public CreateApplicationRequest websocket(@javax.annotation.Nullable Boolean websocket) {
    this.websocket = websocket;
    return this;
  }

  /**
   * Get websocket
   * @return websocket
   */
  @javax.annotation.Nullable
  public Boolean getWebsocket() {
    return websocket;
  }

  public void setWebsocket(@javax.annotation.Nullable Boolean websocket) {
    this.websocket = websocket;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateApplicationRequest createApplicationRequest = (CreateApplicationRequest) o;
    return Objects.equals(this.name, createApplicationRequest.name) &&
        Objects.equals(this.applicationAcceleration, createApplicationRequest.applicationAcceleration) &&
        Objects.equals(this.deliveryProtocol, createApplicationRequest.deliveryProtocol) &&
        Objects.equals(this.originType, createApplicationRequest.originType) &&
        Objects.equals(this.address, createApplicationRequest.address) &&
        Objects.equals(this.minimumTlsVersion, createApplicationRequest.minimumTlsVersion) &&
        Objects.equals(this.originProtocolPolicy, createApplicationRequest.originProtocolPolicy) &&
        Objects.equals(this.hostHeader, createApplicationRequest.hostHeader) &&
        Objects.equals(this.browserCacheSettings, createApplicationRequest.browserCacheSettings) &&
        Objects.equals(this.cdnCacheSettings, createApplicationRequest.cdnCacheSettings) &&
        Objects.equals(this.browserCacheSettingsMaximumTtl, createApplicationRequest.browserCacheSettingsMaximumTtl) &&
        Objects.equals(this.cdnCacheSettingsMaximumTtl, createApplicationRequest.cdnCacheSettingsMaximumTtl) &&
        Objects.equals(this.debugRules, createApplicationRequest.debugRules) &&
        Objects.equals(this.supportedCiphers, createApplicationRequest.supportedCiphers) &&
        Objects.equals(this.httpPort, createApplicationRequest.httpPort) &&
        Objects.equals(this.httpsPort, createApplicationRequest.httpsPort) &&
        Objects.equals(this.l2Caching, createApplicationRequest.l2Caching) &&
        Objects.equals(this.http3, createApplicationRequest.http3) &&
        Objects.equals(this.websocket, createApplicationRequest.websocket);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, applicationAcceleration, deliveryProtocol, originType, address, minimumTlsVersion, originProtocolPolicy, hostHeader, browserCacheSettings, cdnCacheSettings, browserCacheSettingsMaximumTtl, cdnCacheSettingsMaximumTtl, debugRules, supportedCiphers, httpPort, httpsPort, l2Caching, http3, websocket);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateApplicationRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    applicationAcceleration: ").append(toIndentedString(applicationAcceleration)).append("\n");
    sb.append("    deliveryProtocol: ").append(toIndentedString(deliveryProtocol)).append("\n");
    sb.append("    originType: ").append(toIndentedString(originType)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    minimumTlsVersion: ").append(toIndentedString(minimumTlsVersion)).append("\n");
    sb.append("    originProtocolPolicy: ").append(toIndentedString(originProtocolPolicy)).append("\n");
    sb.append("    hostHeader: ").append(toIndentedString(hostHeader)).append("\n");
    sb.append("    browserCacheSettings: ").append(toIndentedString(browserCacheSettings)).append("\n");
    sb.append("    cdnCacheSettings: ").append(toIndentedString(cdnCacheSettings)).append("\n");
    sb.append("    browserCacheSettingsMaximumTtl: ").append(toIndentedString(browserCacheSettingsMaximumTtl)).append("\n");
    sb.append("    cdnCacheSettingsMaximumTtl: ").append(toIndentedString(cdnCacheSettingsMaximumTtl)).append("\n");
    sb.append("    debugRules: ").append(toIndentedString(debugRules)).append("\n");
    sb.append("    supportedCiphers: ").append(toIndentedString(supportedCiphers)).append("\n");
    sb.append("    httpPort: ").append(toIndentedString(httpPort)).append("\n");
    sb.append("    httpsPort: ").append(toIndentedString(httpsPort)).append("\n");
    sb.append("    l2Caching: ").append(toIndentedString(l2Caching)).append("\n");
    sb.append("    http3: ").append(toIndentedString(http3)).append("\n");
    sb.append("    websocket: ").append(toIndentedString(websocket)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("application_acceleration");
    openapiFields.add("delivery_protocol");
    openapiFields.add("origin_type");
    openapiFields.add("address");
    openapiFields.add("minimum_tls_version");
    openapiFields.add("origin_protocol_policy");
    openapiFields.add("host_header");
    openapiFields.add("browser_cache_settings");
    openapiFields.add("cdn_cache_settings");
    openapiFields.add("browser_cache_settings_maximum_ttl");
    openapiFields.add("cdn_cache_settings_maximum_ttl");
    openapiFields.add("debug_rules");
    openapiFields.add("supported_ciphers");
    openapiFields.add("http_port");
    openapiFields.add("https_port");
    openapiFields.add("l2_caching");
    openapiFields.add("http3");
    openapiFields.add("websocket");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("name");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateApplicationRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateApplicationRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateApplicationRequest is not found in the empty JSON string", CreateApplicationRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateApplicationRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateApplicationRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateApplicationRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("delivery_protocol") != null && !jsonObj.get("delivery_protocol").isJsonNull()) && !jsonObj.get("delivery_protocol").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `delivery_protocol` to be a primitive type in the JSON string but got `%s`", jsonObj.get("delivery_protocol").toString()));
      }
      if ((jsonObj.get("origin_type") != null && !jsonObj.get("origin_type").isJsonNull()) && !jsonObj.get("origin_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `origin_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("origin_type").toString()));
      }
      if ((jsonObj.get("address") != null && !jsonObj.get("address").isJsonNull()) && !jsonObj.get("address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("address").toString()));
      }
      if ((jsonObj.get("minimum_tls_version") != null && !jsonObj.get("minimum_tls_version").isJsonNull()) && !jsonObj.get("minimum_tls_version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `minimum_tls_version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("minimum_tls_version").toString()));
      }
      if ((jsonObj.get("origin_protocol_policy") != null && !jsonObj.get("origin_protocol_policy").isJsonNull()) && !jsonObj.get("origin_protocol_policy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `origin_protocol_policy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("origin_protocol_policy").toString()));
      }
      if ((jsonObj.get("host_header") != null && !jsonObj.get("host_header").isJsonNull()) && !jsonObj.get("host_header").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `host_header` to be a primitive type in the JSON string but got `%s`", jsonObj.get("host_header").toString()));
      }
      if ((jsonObj.get("browser_cache_settings") != null && !jsonObj.get("browser_cache_settings").isJsonNull()) && !jsonObj.get("browser_cache_settings").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `browser_cache_settings` to be a primitive type in the JSON string but got `%s`", jsonObj.get("browser_cache_settings").toString()));
      }
      if ((jsonObj.get("cdn_cache_settings") != null && !jsonObj.get("cdn_cache_settings").isJsonNull()) && !jsonObj.get("cdn_cache_settings").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cdn_cache_settings` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cdn_cache_settings").toString()));
      }
      if ((jsonObj.get("supported_ciphers") != null && !jsonObj.get("supported_ciphers").isJsonNull()) && !jsonObj.get("supported_ciphers").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `supported_ciphers` to be a primitive type in the JSON string but got `%s`", jsonObj.get("supported_ciphers").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateApplicationRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateApplicationRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateApplicationRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateApplicationRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateApplicationRequest>() {
           @Override
           public void write(JsonWriter out, CreateApplicationRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateApplicationRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateApplicationRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateApplicationRequest
   * @throws IOException if the JSON string is invalid with respect to CreateApplicationRequest
   */
  public static CreateApplicationRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateApplicationRequest.class);
  }

  /**
   * Convert an instance of CreateApplicationRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

