/*
 * Edge Application API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApplicationCreateInstanceRequestArgs
 */
public class ApplicationCreateInstanceRequestArgsTest {
    private final ApplicationCreateInstanceRequestArgs model = new ApplicationCreateInstanceRequestArgs();

    /**
     * Model tests for ApplicationCreateInstanceRequestArgs
     */
    @Test
    public void testApplicationCreateInstanceRequestArgs() {
        // TODO: test ApplicationCreateInstanceRequestArgs
    }

}
