/*
 * Edge Function API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateEdgeFunctionRequestJsonArgs
 */
public class CreateEdgeFunctionRequestJsonArgsTest {
    private final CreateEdgeFunctionRequestJsonArgs model = new CreateEdgeFunctionRequestJsonArgs();

    /**
     * Model tests for CreateEdgeFunctionRequestJsonArgs
     */
    @Test
    public void testCreateEdgeFunctionRequestJsonArgs() {
        // TODO: test CreateEdgeFunctionRequestJsonArgs
    }

}
